name = "ModalLogic"
defaultTargets = ["ModalLogic", "Axioms", "Collapse", "Examples"]
leanOptions = []

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.28.0"

[[lean_lib]]
name = "ModalLogic"
globs = ["ModalLogic", "ModalLogic.+"]

[[lean_lib]]
name = "Axioms"

[[lean_lib]]
name = "Collapse"

[[lean_lib]]
name = "Examples"